- name: Install deps
  become: yes
  apt:
    state: latest
    name:
      - build-essential
      - default-jre
      - libbz2-dev
      - libnotify-bin
      - ninja-build
      - php
      - php-mbstring
      - php-xml
      - php-zip
      - python-lxml
      - python3
      - python3-dateutil
      - python3-pip
      - python3-lxml

- name: Install tools
  become: yes
  apt:
    state: latest
    name:
      - google-perftools
