- name: Install utils
  become: yes
  apt:
    state: latest
    name:
      - cmake
      - g++
      - gcc
      - gdb
      - git-gui
      - gitk
      - htop
      - mc
      - ncdu
      - ssh
      - tree
